"<#\n"
".SYNOPSIS\n"
"    Uninstalls WinBtrfs from Windows.\n"
"\n"
".DESCRIPTION\n"
"    Removes WinBtrfs devices, driver packages, service registration, shell\n"
"    extension registry entries, and installed binaries. Run from an elevated\n"
"    PowerShell session. A reboot is strongly recommended after this script\n"
"    completes, especially if btrfs.sys or shellbtrfs.dll were loaded.\n"
"\n"
".PARAMETER InfPath\n"
"    Optional path to btrfs.inf. If omitted, the script looks beside the script\n"
"    and in the repository's src directory.\n"
"\n"
".PARAMETER Force\n"
"    Forces removal of matching driver packages when pnputil supports it.\n"
"\n"
".PARAMETER KeepDriverStore\n"
"    Skips pnputil driver package deletion and only disables/removes the live\n"
"    service, registry entries, and copied binaries.\n"
"\n"
".EXAMPLE\n"
"    powershell.exe -ExecutionPolicy Bypass -File .\\uninstall-winbtrfs.ps1 -Force\n"
"#>\n"
"[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]\n"
"param(\n"
"    [Parameter()]\n"
"    [string]$InfPath,\n"
"\n"
"    [Parameter()]\n"
"    [switch]$Force,\n"
"\n"
"    [Parameter()]\n"
"    [switch]$KeepDriverStore\n"
")\n"
"\n"
"Set-StrictMode -Version 2.0\n"
"$ErrorActionPreference = 'Stop'\n"
"\n"
"function Test-Administrator {\n"
"    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()\n"
"    $principal = [Security.Principal.WindowsPrincipal]::new($identity)\n"
"    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)\n"
"}\n"
"\n"
"function Write-Step {\n"
"    param([Parameter(Mandatory = $true)][string]$Message)\n"
"    Write-Host \"==> $Message\" -ForegroundColor Cyan\n"
"}\n"
"\n"
"function Invoke-External {\n"
"    param(\n"
"        [Parameter(Mandatory = $true)][string]$FilePath,\n"
"        [Parameter(Mandatory = $true)][string[]]$Arguments,\n"
"        [Parameter(Mandatory = $true)][string]$Description,\n"
"        [int[]]$AllowedExitCodes = @(0)\n"
"    )\n"
"\n"
"    $commandLine = \"$FilePath $($Arguments -join ' ')\"\n"
"    if (-not $PSCmdlet.ShouldProcess($Description, $commandLine)) {\n"
"        return @()\n"
"    }\n"
"\n"
"    Write-Host \"+ $commandLine\"\n"
"    $output = & $FilePath @Arguments 2>&1\n"
"    $exitCode = $LASTEXITCODE\n"
"    if ($output) {\n"
"        $output | ForEach-Object { Write-Host $_ }\n"
"    }\n"
"\n"
"    if ($AllowedExitCodes -notcontains $exitCode) {\n"
"        Write-Warning \"$Description exited with code $exitCode. Continuing because WinBtrfs may already be partially removed.\"\n"
"    }\n"
"\n"
"    return $output\n"
"}\n"
"\n"
"function Resolve-WinBtrfsInfPath {\n"
"    param([string]$RequestedPath)\n"
"\n"
"    $candidates = @()\n"
"    if ($RequestedPath) {\n"
"        $candidates += $RequestedPath\n"
"    }\n"
"    if ($PSScriptRoot) {\n"
"        $candidates += (Join-Path $PSScriptRoot 'btrfs.inf')\n"
"        $candidates += (Join-Path $PSScriptRoot 'src\\btrfs.inf')\n"
"    }\n"
"    $candidates += (Join-Path (Get-Location) 'btrfs.inf')\n"
"    $candidates += (Join-Path (Get-Location) 'src\\btrfs.inf')\n"
"\n"
"    foreach ($candidate in $candidates | Select-Object -Unique) {\n"
"        if ($candidate -and (Test-Path -LiteralPath $candidate -PathType Leaf)) {\n"
"            return (Resolve-Path -LiteralPath $candidate).Path\n"
"        }\n"
"    }\n"
"\n"
"    return $null\n"
"}\n"
"\n"
"function New-DriverPackageRecord {\n"
"    return @{\n"
"        PublishedName = ''\n"
"        OriginalName = ''\n"
"        ProviderName = ''\n"
"        ClassName = ''\n"
"        DriverVersion = ''\n"
"        SignerName = ''\n"
"    }\n"
"}\n"
"\n"
"function Get-PnpUtilDriverPackages {\n"
"    $output = Invoke-External -FilePath 'pnputil.exe' -Arguments @('/enum-drivers') -Description 'Enumerate driver packages' -AllowedExitCodes @(0)\n"
"    $packages = @()\n"
"    $current = New-DriverPackageRecord\n"
"\n"
"    foreach ($line in $output) {\n"
"        $text = [string]$line\n"
"        if ([string]::IsNullOrWhiteSpace($text)) {\n"
"            if ($current.Count -gt 0) {\n"
"                $packages += [pscustomobject]$current\n"
"                $current = New-DriverPackageRecord\n"
"            }\n"
"            continue\n"
"        }\n"
"\n"
"        if ($text -match '^\\s*([^:]+):\\s*(.*)$') {\n"
"            $name = $matches[1].Trim()\n"
"            $value = $matches[2].Trim()\n"
"            switch -Regex ($name) {\n"
"                '^Published Name$' { $current['PublishedName'] = $value; break }\n"
"                '^Original Name$' { $current['OriginalName'] = $value; break }\n"
"                '^Provider Name$' { $current['ProviderName'] = $value; break }\n"
"                '^Class Name$' { $current['ClassName'] = $value; break }\n"
"                '^Driver Version$' { $current['DriverVersion'] = $value; break }\n"
"                '^Signer Name$' { $current['SignerName'] = $value; break }\n"
"            }\n"
"        }\n"
"    }\n"
"\n"
"    if ($current.Count -gt 0) {\n"
"        $packages += [pscustomobject]$current\n"
"    }\n"
"\n"
"    return $packages | Where-Object {\n"
"        ($_.OriginalName -in @('btrfs.inf', 'btrfs-vol.inf')) -or\n"
"        (($_.ProviderName -eq 'Mark Harmstone') -and ($_.PublishedName -like 'oem*.inf') -and ($_.ClassName -eq 'Volume'))\n"
"    }\n"
"}\n"
"\n"
"function Remove-RegistryPathIfPresent {\n"
"    param([Parameter(Mandatory = $true)][string]$Path)\n"
"\n"
"    if (Test-Path -LiteralPath $Path) {\n"
"        if ($PSCmdlet.ShouldProcess($Path, 'Remove registry key')) {\n"
"            Remove-Item -LiteralPath $Path -Recurse -Force\n"
"            Write-Host \"Removed registry key $Path\"\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"function Add-PendingDeleteSupport {\n"
"    if ('WinBtrfsUninstall.NativeMethods' -as [type]) {\n"
"        return\n"
"    }\n"
"\n"
"    $source = @'\n"
"using System;\n"
"using System.Runtime.InteropServices;\n"
"\n"
"namespace WinBtrfsUninstall {\n"
"    public static class NativeMethods {\n"
"        [DllImport(\"kernel32.dll\", SetLastError = true, CharSet = CharSet.Unicode)]\n"
"        public static extern bool MoveFileEx(string lpExistingFileName, string lpNewFileName, int dwFlags);\n"
"    }\n"
"}\n"
"'@\n"
"    Add-Type -TypeDefinition $source\n"
"}\n"
"\n"
"function Remove-FileOrScheduleDelete {\n"
"    param([Parameter(Mandatory = $true)][string]$Path)\n"
"\n"
"    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {\n"
"        return\n"
"    }\n"
"\n"
"    if (-not $PSCmdlet.ShouldProcess($Path, 'Remove installed file')) {\n"
"        return\n"
"    }\n"
"\n"
"    try {\n"
"        Remove-Item -LiteralPath $Path -Force\n"
"        Write-Host \"Removed $Path\"\n"
"    }\n"
"    catch {\n"
"        Add-PendingDeleteSupport\n"
"        $moveFileDelayUntilReboot = 0x4\n"
"        $scheduled = [WinBtrfsUninstall.NativeMethods]::MoveFileEx($Path, $null, $moveFileDelayUntilReboot)\n"
"        if ($scheduled) {\n"
"            Write-Warning \"$Path is in use and has been scheduled for deletion on reboot.\"\n"
"        }\n"
"        else {\n"
"            $lastError = [Runtime.InteropServices.Marshal]::GetLastWin32Error()\n"
"            Write-Warning \"Could not remove or schedule deletion for $Path. Win32 error: $lastError\"\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"$isWindowsHost = $true\n"
"if (Test-Path -LiteralPath 'Variable:IsWindows') {\n"
"    $isWindowsHost = $IsWindows\n"
"}\n"
"if (-not $isWindowsHost) {\n"
"    throw 'This script must be run on Windows.'\n"
"}\n"
"\n"
"if (-not (Test-Administrator)) {\n"
"    throw 'Run this script from an elevated PowerShell session (Run as Administrator).'\n"
"}\n"
"\n"
"Write-Warning 'Unmount or disconnect Btrfs volumes before continuing. A reboot is recommended when the script finishes.'\n"
"\n"
"$resolvedInfPath = Resolve-WinBtrfsInfPath -RequestedPath $InfPath\n"
"if ($resolvedInfPath) {\n"
"    Write-Step \"Running INF uninstall using $resolvedInfPath\"\n"
"    Invoke-External -FilePath 'rundll32.exe' -Arguments @('setupapi.dll,InstallHinfSection', 'DefaultUninstall', '132', $resolvedInfPath) -Description 'Run btrfs.inf DefaultUninstall' -AllowedExitCodes @(0) | Out-Null\n"
"}\n"
"else {\n"
"    Write-Warning 'btrfs.inf was not found. Continuing with service, registry, driver-store, and file cleanup.'\n"
"}\n"
"\n"
"Write-Step 'Removing WinBtrfs root devices when present'\n"
"$devices = @()\n"
"if (Get-Command Get-PnpDevice -ErrorAction SilentlyContinue) {\n"
"    $devices = Get-PnpDevice -ErrorAction SilentlyContinue | Where-Object {\n"
"        ($_.InstanceId -like 'ROOT\\BTRFS\\*') -or\n"
"        ($_.InstanceId -like 'BtrfsVolume*') -or\n"
"        ($_.FriendlyName -in @('Btrfs controller', 'Btrfs volume'))\n"
"    }\n"
"}\n"
"foreach ($device in $devices) {\n"
"    Invoke-External -FilePath 'pnputil.exe' -Arguments @('/remove-device', $device.InstanceId) -Description \"Remove PnP device $($device.InstanceId)\" -AllowedExitCodes @(0, 259) | Out-Null\n"
"}\n"
"\n"
"Write-Step 'Disabling and deleting the btrfs service'\n"
"Invoke-External -FilePath 'sc.exe' -Arguments @('stop', 'btrfs') -Description 'Stop btrfs service' -AllowedExitCodes @(0, 1060, 1062, 1052) | Out-Null\n"
"Invoke-External -FilePath 'sc.exe' -Arguments @('config', 'btrfs', 'start=', 'disabled') -Description 'Disable btrfs service' -AllowedExitCodes @(0, 1060) | Out-Null\n"
"Invoke-External -FilePath 'sc.exe' -Arguments @('delete', 'btrfs') -Description 'Delete btrfs service' -AllowedExitCodes @(0, 1060, 1072) | Out-Null\n"
"\n"
"if (-not $KeepDriverStore) {\n"
"    Write-Step 'Deleting WinBtrfs driver packages from the driver store'\n"
"    $packages = Get-PnpUtilDriverPackages\n"
"    foreach ($package in $packages) {\n"
"        $arguments = @('/delete-driver', $package.PublishedName, '/uninstall')\n"
"        if ($Force) {\n"
"            $arguments += '/force'\n"
"        }\n"
"        Invoke-External -FilePath 'pnputil.exe' -Arguments $arguments -Description \"Delete driver package $($package.PublishedName)\" -AllowedExitCodes @(0, 2, 3, 5) | Out-Null\n"
"    }\n"
"}\n"
"\n"
"Write-Step 'Removing WinBtrfs shell extension registry entries'\n"
"$registryPaths = @(\n"
"    'Registry::HKEY_CLASSES_ROOT\\*\\ShellEx\\PropertySheetHandlers\\WinBtrfs',\n"
"    'Registry::HKEY_CLASSES_ROOT\\Directory\\Background\\ShellEx\\ContextMenuHandlers\\WinBtrfs',\n"
"    'Registry::HKEY_CLASSES_ROOT\\Drive\\ShellEx\\PropertySheetHandlers\\WinBtrfs',\n"
"    'Registry::HKEY_CLASSES_ROOT\\Folder\\ShellEx\\ContextMenuHandlers\\WinBtrfs',\n"
"    'Registry::HKEY_CLASSES_ROOT\\Folder\\ShellEx\\PropertySheetHandlers\\WinBtrfs',\n"
"    'Registry::HKEY_CLASSES_ROOT\\CLSID\\{2690B74F-F353-422D-BB12-401581EEF8F0}',\n"
"    'Registry::HKEY_CLASSES_ROOT\\CLSID\\{2690B74F-F353-422D-BB12-401581EEF8F1}',\n"
"    'Registry::HKEY_CLASSES_ROOT\\CLSID\\{2690B74F-F353-422D-BB12-401581EEF8F2}',\n"
"    'Registry::HKEY_CLASSES_ROOT\\CLSID\\{2690B74F-F353-422D-BB12-401581EEF8F3}',\n"
"    'Registry::HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\btrfs'\n"
")\n"
"foreach ($path in $registryPaths) {\n"
"    Remove-RegistryPathIfPresent -Path $path\n"
"}\n"
"\n"
"Write-Step 'Removing installed WinBtrfs binaries'\n"
"$systemRoot = $env:SystemRoot\n"
"$installedFiles = @(\n"
"    (Join-Path $systemRoot 'System32\\drivers\\btrfs.sys'),\n"
"    (Join-Path $systemRoot 'System32\\shellbtrfs.dll'),\n"
"    (Join-Path $systemRoot 'System32\\ubtrfs.dll'),\n"
"    (Join-Path $systemRoot 'System32\\mkbtrfs.exe')\n"
")\n"
"foreach ($file in $installedFiles) {\n"
"    Remove-FileOrScheduleDelete -Path $file\n"
"}\n"
"\n"
"Write-Step 'WinBtrfs uninstall cleanup complete'\n"
"Write-Host 'Reboot Windows now to unload any remaining driver or shell-extension references.' -ForegroundColor Yellow\n"
